### PR TITLE
Added del-cli and cross-env for package scripts to work on Windows

### LINKED ISSUE #39: I get an error when running command BABEL_ENV=es6
I am a Windows dev (please don't shun me) and running scripts on `package.jsn` that have the setting `BABEL_ENV=xxx` causes an error. Also happens with `rimraf`, which I can overcome with replacing it with `del-cli` package.

Please consider making the scripts Windows friendly ;)

### PR DESCRIPTION
**Pull request by alebrozzo**
closes #39

### CODE REVIEW

**Comment by bebraw** [comment]
Thanks. 👍

**Comment by bebraw** [comment]
Note that I'm looking for active maintainers for the boilerplate. It likely does a little too much but some of the ideas are solid.

**Comment by alebrozzo** [comment]
Thank _you_! I still don't feel confident enough to be able to maintain such a project and I don't create components so often as to use it much, but if I do get to the point of actually knowing what I am doing, I will gladly help!
BTW, I followed your webpack and react tutorials and I _did_ promised (via Disquss) to buy you coffee if I was able to change jobs thanks to them... which I did, and I'd like to pay my debt now. How could I buy you a coffee / donate to any of your projects, if any?

**Comment by bebraw** [comment]
> BTW, I followed your webpack and react tutorials and I did promised (via Disquss) to buy you coffee if I was able to change jobs thanks to them... which I did, and I'd like to pay my debt now. How could I buy you a coffee / donate to any of your projects, if any?

I'm happy with the PR, thanks! Maybe you can buy a book from me unless you did already. 👍

**Comment by alebrozzo** [comment]
I'll probably do that then! can you point me to the right link?

**Comment by bebraw** [comment]
Here's the [bundle](https://leanpub.com/b/survivejs-webpack-react). Note that the webpack book comes with some extra bits (poster, cheatsheet, QA with Tobias).

You can also find the webpack book on Kindle (about $10).

**Comment by alebrozzo** [comment]
Done! Bought the React only but paid more than the minimum because I wanted you to have that coffee :D

**Pull request merged**
